In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
https://raw.githubusercontent.com/SyedZakkariya/exp1ml/refs/heads/main/student_performance_updated_1000.csv

In [2]:
dataset = "https://raw.githubusercontent.com/SyedZakkariya/exp1ml/refs/heads/main/student_performance_updated_1000.csv"
student = pd.read_csv(dataset)
student.head()

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True

In [3]:
print("Dataset Shape:",student.shape)
print("No of Rows",student.shape[0])
print("No of Columnss",student.shape[1])

Dataset Shape: (1000, 12)
No of Rows 1000
No of Columnss 12

In [4]:
print("\nColumn Names:")
print(student.columns)

Column Names:
Index(['StudentID', 'Name', 'Gender', 'AttendanceRate', 'StudyHoursPerWeek',
       'PreviousGrade', 'ExtracurricularActivities', 'ParentalSupport',
       'FinalGrade', 'Study Hours', 'Attendance (%)', 'Online Classes Taken'],
      dtype='object')

In [5]:
print("\nDataset Information:")
print(student.info())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  960 non-null    float64
 1   Name                       966 non-null    object
 2   Gender                     952 non-null    object
 3   AttendanceRate             960 non-null    float64
 4   StudyHoursPerWeek          950 non-null    float64
 5   PreviousGrade              967 non-null    float64
 6   ExtracurricularActivities  957 non-null    float64
 7   ParentalSupport            978 non-null    object
 8   FinalGrade                 960 non-null    float64
 9   Study Hours                976 non-null    float64
 10  Attendance (%)             959 non-null    float64
 11  Online Classes Taken       975 non-null    object
dtypes: float64(8), object(4)
memory usage: 93.9+ KB
None

In [6]:
print("\nStatistical Summary:")
student.describe().transpose()

Statistical Summary:

,count,mean,std,min,25%,50%,75%,max
StudentID,960.0,5416.019792,2653.748319,1.0,3113.5,5396.5,7754.75,9998.0
AttendanceRate,960.0,85.510417,7.332125,70.0,82.0,88.0,91.00,95.0
StudyHoursPerWeek,950.0,17.630526,6.272132,8.0,12.0,18.0,22.00,30.0
PreviousGrade,967.0,77.598759,10.006640,60.0,70.0,78.0,86.00,90.0
ExtracurricularActivities,957.0,1.520376,1.046439,0.0,1.0,1.0,2.00,3.0
FinalGrade,960.0,80.030208,9.493652,62.0,72.0,80.0,88.00,92.0
Study Hours,976.0,2.406967,1.620267,-5.0,1.2,2.5,3.70,5.0
Attendance (%),959.0,77.248175,19.298148,50.0,63.0,76.0,89.00,200.0

In [7]:
student.columns = (
    student.columns
    .str.strip()
    .str.replace(' ', '_')
    .str.replace(r'[%()]', '', regex=True)
)
print(student.columns)

Index(['StudentID', 'Name', 'Gender', 'AttendanceRate', 'StudyHoursPerWeek',
       'PreviousGrade', 'ExtracurricularActivities', 'ParentalSupport',
       'FinalGrade', 'Study_Hours', 'Attendance_', 'Online_Classes_Taken'],
      dtype='object')

In [8]:
student.loc[student['Study_Hours'] < 0, 'Study_Hours'] = np.nan
student.loc[student['Attendance_'] > 100, 'Attendance_'] = np.nan

In [9]:
print(student.isnull().sum())

StudentID                    40
Name                         34
Gender                       48
AttendanceRate               40
StudyHoursPerWeek            50
PreviousGrade                33
ExtracurricularActivities    43
ParentalSupport              22
FinalGrade                   40
Study_Hours                  34
Attendance_                  51
Online_Classes_Taken         25
dtype: int64

In [10]:
student = student.drop(columns=['StudentID', 'Name'])
print(student.columns)

Index(['Gender', 'AttendanceRate', 'StudyHoursPerWeek', 'PreviousGrade',
       'ExtracurricularActivities', 'ParentalSupport', 'FinalGrade',
       'Study_Hours', 'Attendance_', 'Online_Classes_Taken'],
      dtype='object')